[versions]
ktlint = "1.8.0"
ktor = "3.3.3"
kotlin = "2.3.0"
java = "19"
multiplatform-locale = "0.9.0"

[libraries]
androidpublisher = { module = "com.google.apis:google-api-services-androidpublisher", version = "v3-rev20260129-2.0.0" }
clikt = { module = "com.github.ajalt:clikt", version = "2.8.0" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.2"
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }
ktor-client-core-jvm = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
multiplatform-locale = { module = "com.vanniktech:multiplatform-locale", version.ref = "multiplatform-locale" }
multiplatform-locale-google-play-store = { module = "com.vanniktech:multiplatform-locale-google-play-store", version.ref = "multiplatform-locale" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-shadowjar = { module = "com.gradleup.shadow:shadow-gradle-plugin", version = "9.3.1" }

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.25.0" }
